
import { Offer } from './types';

export const MOCK_OFFERS: Offer[] = [
  {
    id: '1',
    title: 'Protocolo Zero Barriga',
    niche: 'Emagrecimento',
    language: 'Português',
    trafficSource: 'Facebook Ads',
    productType: 'Low Ticket',
    structure: 'VSL + Checkout',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=800&auto=format&fit=crop',
    views: 12500,
    transcription: 'Este protocolo foi desenvolvido para quem deseja resultados rápidos sem dietas restritivas. Começamos entendendo o metabolismo...',
    creativeImages: ['https://picsum.photos/seed/c1/200/200', 'https://picsum.photos/seed/c2/200/200']
  },
  {
    id: '2',
    title: 'O Despertar da Prosperidade',
    niche: 'Lei da Atração/Prosperidade',
    language: 'Português',
    trafficSource: 'Google Ads',
    productType: 'Infoproduto',
    structure: 'Webinar',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=800&auto=format&fit=crop',
    views: 8400,
    transcription: 'Mude sua frequência vibracional para atrair abundância financeira em 21 dias...',
    creativeImages: ['https://picsum.photos/seed/c3/200/200']
  },
  {
    id: '3',
    title: 'English Immersion 3.0',
    niche: 'Idiomas',
    language: 'Inglês',
    trafficSource: 'YouTube Ads',
    productType: 'Infoproduto',
    structure: 'Página de Vendas',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800&auto=format&fit=crop',
    views: 15200,
    transcription: 'Aprenda o vocabulário essencial que 95% dos nativos usam no dia a dia. Esqueça a gramática complexa...',
    creativeImages: ['https://picsum.photos/seed/c4/200/200', 'https://picsum.photos/seed/c5/200/200']
  },
  {
    id: '4',
    title: 'Gummy Skin Rejuvenator',
    niche: 'Rejuvenescimento',
    language: 'Português',
    trafficSource: 'TikTok Ads',
    productType: 'Nutracêutico',
    structure: 'Free Trial',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=800&auto=format&fit=crop',
    views: 22000,
    transcription: 'A fórmula secreta das atrizes de Hollywood para manter a pele jovem sem botox...',
    creativeImages: ['https://picsum.photos/seed/c6/200/200']
  },
  {
    id: '5',
    title: 'Super Fone Air Pro',
    niche: 'Outros',
    language: 'Espanhol',
    trafficSource: 'Native Ads',
    productType: 'Dropshipping',
    structure: 'Página Direta',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    views: 5600,
    transcription: 'Som cristalino e cancelamento de ruído por uma fração do preço das marcas famosas...',
    creativeImages: ['https://picsum.photos/seed/c7/200/200', 'https://picsum.photos/seed/c8/200/200']
  },
  {
    id: '6',
    title: 'Próstata Flow 360',
    niche: 'Próstata',
    language: 'Português',
    trafficSource: 'Native Ads',
    productType: 'Nutracêutico',
    structure: 'VSL + Checkout',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=800&auto=format&fit=crop',
    views: 35000,
    transcription: 'Pare de acordar 5 vezes a noite para ir ao banheiro. Conheça o extrato que está salvando a saúde dos homens...',
    creativeImages: ['https://picsum.photos/seed/c9/200/200']
  },
  {
    id: '7',
    title: 'Mestre da Escrita',
    niche: 'Escrita',
    language: 'Português',
    trafficSource: 'Instagram Ads',
    productType: 'Infoproduto',
    structure: 'Direct to WhatsApp',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=800&auto=format&fit=crop',
    views: 4300,
    transcription: 'Torne-se um redator profissional e ganhe em dólar trabalhando de casa...',
    creativeImages: ['https://picsum.photos/seed/c10/200/200']
  },
  {
    id: '8',
    title: 'Curva Zero Articulações',
    niche: 'Dores Articulares',
    language: 'Português',
    trafficSource: 'Facebook Ads',
    productType: 'Nutracêutico',
    structure: 'Sales Page',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
    views: 11200,
    transcription: 'Diga adeus às dores nos joelhos e costas com apenas 2 gotas por dia...',
    creativeImages: ['https://picsum.photos/seed/c11/200/200']
  },
  {
    id: '9',
    title: 'Insta Money Pro',
    niche: 'Renda Extra',
    language: 'Português',
    trafficSource: 'Facebook Ads',
    productType: 'Low Ticket',
    structure: 'Quiz Flow',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop',
    views: 7800,
    transcription: 'O aplicativo secreto que paga para você avaliar anúncios no Instagram...',
    creativeImages: ['https://picsum.photos/seed/c12/200/200', 'https://picsum.photos/seed/c13/200/200']
  },
  {
    id: '10',
    title: 'Cérebro Blindado (Anti-Alzheimer)',
    niche: 'Alzheimer',
    language: 'Português',
    trafficSource: 'Native Ads',
    productType: 'Nutracêutico',
    structure: 'VSL',
    vslUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    facebookUrl: '#',
    pageUrl: '#',
    coverImage: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=800&auto=format&fit=crop',
    views: 31000,
    transcription: 'Proteja quem você ama do esquecimento. Cientistas descobrem nutriente que reverte o declínio cognitivo...',
    creativeImages: ['https://picsum.photos/seed/c14/200/200']
  },
  {
    id: '11',
    title: 'Protocolo Erguendo Gigantes',
    niche: 'Aumento Peniano',
    language: 'Português',
    trafficSource: 'Facebook Ads',
    productType: 'Low Ticket',
    structure: 'VSL + Checkout',
    vslUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    facebookUrl: 'https://www.facebook.com/ads/library/',
    pageUrl: 'https://google.com',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-2173bdd9962a?q=80&w=800&auto=format&fit=crop',
    views: 15400,
    transcription: 'A descoberta que está mudando a vida de milhares de homens. Um método natural e testado para restaurar a confiança...',
    creativeImages: ['https://picsum.photos/seed/c20/200/200', 'https://picsum.photos/seed/c21/200/200']
  }
];
