export const MOCK_OFFERS = [
  {
    id: '1',
    title: 'Protocolo Zero Barriga',
    niche: 'Emagrecimento',
    productType: 'Nutracêutico',
    description: 'Mecanismo único de água morna matinal.',
    coverImage: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800',
    trend: 'Escalando',
    views: 125000,
    vslLinks: [{ label: 'VSL Principal', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script focado em retenção matinal...',
    creativeImages: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400'],
    facebookUrl: 'https://facebook.com/ads/library',
    pageUrl: 'https://google.com',
    language: 'Português',
    trafficSource: ['Facebook', 'TikTok']
  },
  {
    id: '2',
    title: 'SSN Withdrawal - American Method',
    niche: 'Renda Extra',
    productType: 'Infoproduto',
    description: 'Recuperação de taxas americanas.',
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    trend: 'Em Alta',
    views: 89000,
    vslLinks: [{ label: 'VSL Oficial', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script de autoridade financeira...',
    creativeImages: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400'],
    facebookUrl: 'https://facebook.com/ads/library',
    pageUrl: 'https://google.com',
    language: 'Inglês',
    trafficSource: ['Google Ads', 'YouTube']
  },
  {
    id: '3',
    title: 'O Segredo da Milha Aérea',
    niche: 'Finanças',
    productType: 'Infoproduto',
    description: 'Como viajar de graça com cartões.',
    coverImage: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800',
    trend: 'Escalando',
    views: 45000,
    vslLinks: [{ label: 'VSL Vendas', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Transcrição completa aqui...',
    creativeImages: ['https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=400'],
    facebookUrl: 'https://facebook.com/ads/library',
    pageUrl: '#',
    language: 'Português',
    trafficSource: ['Facebook', 'Instagram']
  },
  {
    id: '4',
    title: 'English in 3 Months',
    niche: 'Idiomas',
    productType: 'Infoproduto',
    description: 'Método de imersão acelerada.',
    coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    trend: 'Em Alta',
    views: 67000,
    vslLinks: [{ label: 'VSL Principal', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script focado em poliglotas...',
    creativeImages: ['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400'],
    facebookUrl: 'https://facebook.com/ads/library',
    pageUrl: '#',
    language: 'Inglês',
    trafficSource: ['YouTube', 'Google Ads']
  },
  {
    id: '5',
    title: 'Ads Mastery Pro',
    niche: 'Marketing Digital',
    productType: 'Low Ticket',
    description: 'Gestão de tráfego para iniciantes.',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    trend: 'Escalando',
    views: 32000,
    vslLinks: [{ label: 'VSL 1', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Transcrição do vídeo de vendas...',
    creativeImages: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400'],
    facebookUrl: 'https://facebook.com/ads/library',
    pageUrl: '#',
    language: 'Português',
    trafficSource: ['Facebook', 'Taboola']
  },
  {
    id: '6',
    title: 'Cripto Trader 24h',
    niche: 'Investimentos',
    productType: 'Dropshipping',
    description: 'Sinais de cripto via bot.',
    coverImage: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800',
    trend: 'Em Alta',
    views: 56000,
    vslLinks: [{ label: 'VSL Oficial', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script de escassez e lucros...',
    creativeImages: ['https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=400'],
    facebookUrl: '#',
    pageUrl: '#',
    language: 'Espanhol',
    trafficSource: ['TikTok', 'YouTube']
  },
  {
    id: '7',
    title: 'Skin Care Natural',
    niche: 'Beleza',
    productType: 'Nutracêutico',
    description: 'Rotina coreana de rejuvenescimento.',
    coverImage: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
    trend: 'Escalando',
    views: 91000,
    vslLinks: [{ label: 'VSL Principal', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script focado em colágeno...',
    creativeImages: ['https://images.unsplash.com/photo-1598440494896-20b319420de9?w=400'],
    facebookUrl: '#',
    pageUrl: '#',
    language: 'Português',
    trafficSource: ['Facebook', 'TikTok']
  },
  {
    id: '8',
    title: 'Mestre do Churrasco',
    niche: 'Culinária',
    productType: 'Low Ticket',
    description: 'Cortes nobres e técnicas gregas.',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    trend: 'Em Alta',
    views: 12000,
    vslLinks: [{ label: 'VSL 1', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script de gastronomia...',
    creativeImages: ['https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400'],
    facebookUrl: '#',
    pageUrl: '#',
    language: 'Português',
    trafficSource: ['Facebook', 'Google Ads']
  },
  {
    id: '9',
    title: 'Python for Finance',
    niche: 'Educação',
    productType: 'Infoproduto',
    description: 'Automação de planilhas financeiras.',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
    trend: 'Escalando',
    views: 28000,
    vslLinks: [{ label: 'VSL Aulas', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script focado em produtividade...',
    creativeImages: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400'],
    facebookUrl: '#',
    pageUrl: '#',
    language: 'Inglês',
    trafficSource: ['LinkedIn', 'Google Ads']
  },
  {
    id: '10',
    title: 'Código da Sedução',
    niche: 'Relacionamento',
    productType: 'Infoproduto',
    description: 'Psicologia aplicada social.',
    coverImage: 'https://images.unsplash.com/photo-1516131206008-dd041a9764fd?w=800',
    trend: 'Em Alta',
    views: 156000,
    vslLinks: [{ label: 'VSL Principal', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }],
    downloadUrl: '#',
    transcription: 'Script de gatilhos mentais...',
    creativeImages: ['https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400'],
    facebookUrl: '#',
    pageUrl: '#',
    language: 'Português',
    trafficSource: ['Facebook', 'YouTube']
  }
];
